# This is a basic workflow to help you get started with Actions

name: Publish Static Web Pages to GCP Bucket

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Git to GCS
        uses: nakilon/git-to-gcs@1
        with:
          secrets: ${{ secrets.secrets }}
