name: Publish Static Webpages to Google Cloud Platform Storage Bucket

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: GCP Cloud Storage: Deploy
    - uses: abinmn/gcp-storage-bucket-action@v1.0
      
